"""Create TaskList model

Revision ID: 598b82aa916d
Revises: 9eb4a3cb8005
Create Date: 2024-03-16 15:52:14.266369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '598b82aa916d'
down_revision: Union[str, None] = '9eb4a3cb8005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasklist',
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('task', sa.Column('tasklist_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'task', 'tasklist', ['tasklist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'tasklist_id')
    op.drop_table('tasklist')
    # ### end Alembic commands ###
